EU-OSHA/oira-D9

config/sync/core.entity_form_display.taxonomy_term.promotional_material_type.default.yml
config/sync/core.entity_form_display.taxonomy_term.tags.default.yml
config/sync/core.entity_view_display.taxonomy_term.promotional_material_type.default.yml
config/sync/core.entity_view_display.taxonomy_term.tags.default.yml
config/sync/field.field.taxonomy_term.promotional_material_type.field_image.yml
config/sync/field.field.taxonomy_term.tags.field_code.yml
config/sync/field.field.taxonomy_term.tags.field_excluded_from.yml
config/sync/field.storage.taxonomy_term.field_code.yml
config/sync/field.storage.taxonomy_term.field_excluded_from.yml
config/sync/field.storage.taxonomy_term.field_image.yml

Add pending fields to taxonomies

---

config/sync/image.style.views_thumbail.yml
config/sync/views.view.oira_ws.yml

Add image styles.
Update OiRA Tools View

MOIRA-44 - New Theme

---

config/sync/views.view.news.yml

Config revision

---

config/sync/better_social_sharing_buttons.settings.yml
config/sync/block.block.exposedformoira_wstools_ws.yml
config/sync/core.base_field_override.node.external_url.promote.yml
config/sync/core.entity_form_display.node.external_url.default.yml
config/sync/core.entity_view_display.node.article.default.yml
config/sync/core.entity_view_display.node.article.rss.yml
config/sync/core.entity_view_display.node.article.search_index.yml
config/sync/core.entity_view_display.node.article.search_result.yml
config/sync/core.entity_view_display.node.article.teaser.yml
config/sync/core.entity_view_display.node.external_url.additional_resource.yml
config/sync/core.entity_view_display.node.external_url.default.yml
config/sync/core.entity_view_display.node.external_url.teaser.yml
config/sync/core.extension.yml
config/sync/field.field.node.article.field_aditional_resources.yml
config/sync/field.field.node.external_url.body.yml
config/sync/field.field.node.external_url.field_character_count.yml
config/sync/field.field.node.external_url.field_external_url.yml
config/sync/field.field.node.external_url.field_image.yml
config/sync/field.field.node.external_url.field_page_count.yml
config/sync/field.storage.node.field_external_url.yml
config/sync/language.content_settings.node.external_url.yml
config/sync/language/fr/webform.webform.contact.yml
config/sync/language/nl/webform.webform.contact.yml
config/sync/node.type.external_url.yml
config/sync/views.view.additional_resources.yml
config/sync/views.view.additional_resources_admin.yml
config/sync/views.view.aditional_resources.yml
config/sync/views.view.promotional_materials.yml
config/sync/views.view.tools.yml

Revise views: tools, promotional materials, aditional resources
Add content type external_url
Add view Aditional resources admin
Enable and configure better social sharing buttons (pending enable block at end of articles and configure field social sharing buttons and revise if it works. Linkedin does not work)

Views revision

---

config/sync/core.base_field_override.node.certificates.status.yml
config/sync/core.base_field_override.node.file.promote.yml
config/sync/core.entity_form_display.node.certificates.default.yml
config/sync/core.entity_form_display.node.file.default.yml
config/sync/core.entity_view_display.node.certificates.default.yml
config/sync/core.entity_view_display.node.certificates.teaser.yml
config/sync/core.entity_view_display.node.file.default.yml
config/sync/core.entity_view_display.node.file.teaser.yml
config/sync/field.field.media.resource_fc.field_media_file.yml
config/sync/field.field.node.certificates.body.yml
config/sync/field.field.node.certificates.field_workbench_access.yml
config/sync/field.field.node.file.field_file.yml
config/sync/field.storage.node.field_file.yml
config/sync/language.content_settings.node.certificates.yml
config/sync/language.content_settings.node.file.yml
config/sync/node.type.certificates.yml
config/sync/node.type.file.yml
config/sync/views.view.certificates.yml
config/sync/views.view.promotional_resources_admin.yml
config/sync/views.view.related_partner.yml
config/sync/views.view.related_partners.yml

Add content type Certificates + view 
Add content type File
Add Promotional resources admin
Add Related partner view

Views added

---

config/sync/core.extension.yml
config/sync/user.role.editor.yml
config/sync/user.role.partner.yml
config/sync/views.view.moderated_content.yml
config/sync/workflows.workflow.editorial.yml
config/sync/workflows.workflow.oira.yml

Enable modules:
-  content moderation
-  content moderation notification
-  workflow
Create workflow oira
Create states, transitions and define contents for workflow
Update role Editor permissions for workflow.

Content moderation

---

config/sync/core.entity_view_display.node.news.additional_resource.yml
config/sync/core.entity_view_display.node.news.default.yml
config/sync/core.entity_view_display.node.news.teaser.yml
config/sync/core.entity_view_display.node.practical_tool.additional_resource.yml
config/sync/core.entity_view_display.node.practical_tool.country_partner_content.yml
config/sync/core.entity_view_display.node.practical_tool.osha_resources.yml
config/sync/core.entity_view_display.node.practical_tool.osha_wiki.yml
config/sync/core.entity_view_display.node.practical_tool.search_index.yml
config/sync/core.entity_view_display.node.promotional_material.default.yml
config/sync/core.entity_view_display.node.promotional_material.teaser.yml
config/sync/views.view.faqs_oira.yml
config/sync/views.view.moderated_content.yml

Create in view moderated_content the displays:
- Project Manager NR
- Review Manager NR
- My Content
This displays can be found in D7 in view Osh Workflow Admin

Add views for content moderation

---

config/sync/block.block.language.yml
config/sync/devel.toolbar.settings.yml
config/sync/facets.facet.country.yml
config/sync/facets.facet.language.yml
config/sync/facets.facet.sector.yml
config/sync/migrate_plus.migration.oira_taxonomy_sector_category.yml
config/sync/migrate_plus.migration.oira_taxonomy_sector_category_i18n.yml
config/sync/search_api.index.oira_tools.yml
config/sync/views.view.oira_ws.yml
config/sync/views.view.terminos_migration.yml
config/sync/workflows.workflow.oira.yml

Fix language facet in view oira tools

Tools review

---

config/sync/views.view.country_partner_content.yml
config/sync/views.view.partner_content.yml

Add view Partner Content
Add view Partner Content Tabs

Partners private zone views

---

config/sync/core.entity_form_display.node.news.default.yml
config/sync/core.entity_form_display.node.practical_tool.default.yml
config/sync/core.entity_form_display.node.promotional_material.default.yml
config/sync/core.entity_view_display.node.news.additional_resource.yml
config/sync/core.entity_view_display.node.news.default.yml
config/sync/core.entity_view_display.node.news.teaser.yml
config/sync/core.entity_view_display.node.partner.related_partner.yml
config/sync/core.entity_view_display.node.practical_tool.additional_resource.yml
config/sync/core.entity_view_display.node.practical_tool.country_partner_content.yml
config/sync/core.entity_view_display.node.practical_tool.default.yml
config/sync/core.entity_view_display.node.practical_tool.osha_resources.yml
config/sync/core.entity_view_display.node.practical_tool.osha_wiki.yml
config/sync/core.entity_view_display.node.practical_tool.search_index.yml
config/sync/core.entity_view_display.node.practical_tool.search_result.yml
config/sync/core.entity_view_display.node.practical_tool.teaser.yml
config/sync/core.entity_view_display.node.promotional_material.default.yml
config/sync/core.entity_view_display.node.promotional_material.teaser.yml
config/sync/core.entity_view_mode.node.related_partner.yml
config/sync/field.field.node.news.field_co_author_node.yml
config/sync/field.field.node.news.field_related_partners.yml
config/sync/field.field.node.practical_tool.field_co_author_node.yml
config/sync/field.field.node.promotional_material.field_co_author_node.yml
config/sync/field.storage.node.field_co_author_node.yml
config/sync/views.view.promotional_materials.yml
config/sync/views.view.tools.yml

Add fields co_author_node and related_partners to content type news, oira tools, promotional resources.
Fix views tools block latest tools and promotional materials for block in home page

Views with related partners and co-author

---

config/sync/block.block.exposedformoira_wstools_ws.yml
config/sync/block.block.oira_theme_content.yml
config/sync/block.block.oira_theme_help.yml
config/sync/block.block.oira_theme_local_actions.yml
config/sync/block.block.oira_theme_local_tasks.yml
config/sync/block.block.oira_theme_page_title.yml
config/sync/block.block.views_block__additional_resources_block.yml
config/sync/block.block.views_block__news_block_1.yml
config/sync/block.block.views_block__news_block_2.yml
config/sync/core.entity_view_display.node.article.additional_resource.yml
config/sync/views.view.additional_resources.yml
config/sync/views.view.country_partner_content.yml
config/sync/views.view.oira_partners.yml
config/sync/views.view.oira_ws.yml
config/sync/views.view.promotional_materials.yml
config/sync/views.view.tools.yml

Add blocks related news and additional resources to article what-risk-assessment
Update views with field related partners and co author node

Views related partners

---

config/sync/block.block.country.yml
config/sync/block.block.countryforsearchsite.yml
config/sync/block.block.countrytaxonomytermnamepromoresources.yml
config/sync/block.block.exposedformoira_wstools_ws.yml
config/sync/block.block.exposedformoira_wstools_ws_2.yml
config/sync/block.block.exposedformpromotional_resources_searchpage_1.yml
config/sync/block.block.exposedformpromotional_resources_searchpage_1_2.yml
config/sync/block.block.exposedformsearchpage_1.yml
config/sync/block.block.language.yml
config/sync/block.block.oira_theme_content.yml
config/sync/block.block.resourcemedialanguagenameresource.yml
config/sync/block.block.sector.yml
config/sync/block.block.sectorcategoryforsearchsite.yml
config/sync/block.block.type.yml
config/sync/block.block.views_block__additional_resources_block.yml
config/sync/block.block.views_block__country_partner_content_block_1.yml
config/sync/block.block.views_block__country_partner_content_block_3.yml
config/sync/block.block.views_block__country_partner_content_block_5.yml
config/sync/block.block.views_block__news_block_1.yml
config/sync/block.block.views_block__news_block_2.yml
config/sync/block.block.views_block__tools_block_2.yml
config/sync/views.view.faqs_oira.yml
config/sync/views.view.promotional_resources_search.yml
config/sync/views.view.search.yml
config/sync/views.view.tools.yml

Fix height settings in view faq
Add filter translation language to view faqs
Add classes to view tools block new tools
Add fields and exposed form to view promotional materials search
Add fields to view search

View fixes

---

config/sync/block.block.exposedformsearchpage_1_2.yml
config/sync/block.block.oira_theme_help.yml
config/sync/block.block.oira_theme_local_actions.yml
config/sync/block.block.oira_theme_local_tasks.yml
config/sync/block.block.oira_theme_page_title.yml
config/sync/search.page.search_site.yml
config/sync/search_api.index.default_multilingual_node_index.yml
config/sync/views.view.promotional_resources_search.yml
config/sync/views.view.search.yml

Update view search to show each type of content with different fields
Fix promotional resources search field body with strip tags

Update view search site with proper displays for each type of content

---

config/sync/core.entity_view_display.media.collaboration_items.media_library.yml
config/sync/core.entity_view_display.node.collaboration_document.teaser.yml
config/sync/image.style.medium_thumbnail_mc_525_x_360_.yml
config/sync/views.view.eu_osha_files.yml
config/sync/views.view.private_images.yml
config/sync/views.view.private_images_admin.yml

Add view EU-OSHA Files, Private images, Private images admin for https://oiraproject.eu/en/private-zone/collaboration-area EU-OSHA Files

Euosha files

---

config/sync/block.block.headerviewoiraotherpartners.yml
config/sync/core.entity_form_display.node.practical_tool.default.yml
config/sync/core.entity_view_display.node.practical_tool.additional_resource.yml
config/sync/core.entity_view_display.node.practical_tool.country_partner_content.yml
config/sync/core.entity_view_display.node.practical_tool.default.yml
config/sync/core.entity_view_display.node.practical_tool.osha_resources.yml
config/sync/core.entity_view_display.node.practical_tool.osha_wiki.yml
config/sync/core.entity_view_display.node.practical_tool.search_index.yml
config/sync/core.entity_view_display.node.practical_tool.search_result.yml
config/sync/core.entity_view_display.node.practical_tool.teaser.yml
config/sync/field.field.node.practical_tool.field_co_author_node.yml
config/sync/field.field.node.practical_tool.field_language.yml
config/sync/field.field.node.practical_tool.field_related_partners.yml
config/sync/field.field.node.practical_tool.field_third_language.yml
config/sync/field.field.node.practical_tool.field_third_partner.yml
config/sync/field.field.node.practical_tool.field_third_partner_node.yml
config/sync/field.storage.node.field_third_partner.yml
config/sync/field.storage.node.field_third_partner_node.yml
config/sync/views.view.country_partner_reference_view.yml
config/sync/views.view.faqs_oira.yml
config/sync/views.view.partner_taxonomy_reference_view.yml
config/sync/views.view.partners_list.yml

Secure develop

---

config/local/search_api.server.apachesolr.yml
config/sync/content_moderation_notifications.content_moderation_notification.notification_partner_content_created.yml
config/sync/content_moderation_notifications.content_moderation_notification.notification_partners_users_when_to_be_reviewed.yml
config/sync/content_moderation_notifications.content_moderation_notification.notification_when_published.yml
config/sync/content_moderation_notifications.content_moderation_notification.notification_when_to_be_approved.yml
config/sync/content_moderation_notifications.content_moderation_notification.notification_when_to_be_reviewed_for_project_manager_.yml
config/sync/content_moderation_notifications.content_moderation_notification.notify_partner_when_his_content_published.yml
config/sync/field.field.node.practical_tool.field_language.yml
config/sync/field.field.node.practical_tool.field_third_language.yml

Create content moderation notifications
Fix language label in oira tools

Content notifications

---

config/local/search_api.index.oira_tools.yml
config/local/views.view.oira_ws.yml
config/sync/block.block.headerviewfaqsoira.yml
config/sync/block.block.headerviewotherpartners.yml
config/sync/core.extension.yml
config/sync/crop.settings.yml
config/sync/field.storage.node.field_language.yml
config/sync/image.style.crop_thumbnail.yml
config/sync/image_widget_crop.settings.yml
config/sync/language.content_settings.path_alias.path_alias.yml
config/sync/languagefield.custom_language.mt.yml
config/sync/languagefield.custom_language.pt.yml
config/sync/pathauto.pattern.article.yml
config/sync/user.role.anonymous.yml
config/sync/views.view.faqs_oira.yml
config/sync/views.view.partner_intro_info.yml
config/sync/views.view.promotional_materials_type.yml

Fix faqs oira
Add others partners title
Fix oira tool language facet portuguese and maltese
give anonymous user permission to see media
Update alias and node partner
Enable modules crop api and image widget crop

Trello fixes

---

config/staging/facets.facet.country_search_facet.yml
config/staging/facets.facet.sector_category_for_search_site.yml
config/staging/facets.facet.type.yml
config/staging/search_api.index.promotional_resources.yml
config/staging/views.view.oira_ws.yml
config/staging/views.view.promotional_resources_search.yml
config/staging/views.view.search.yml
config/sync/pathauto.pattern.news.yml

https://drive.google.com/file/d/1H6LX4Cb2_f6C-JPDy1S0TyCGpEkzE21n/view?usp=sharing

Fix facets deploy

---

config/sync/views.view.moderated_content.yml

Última BBDD con traducciones de slide: https://drive.google.com/file/d/1EIRrzXCYuvKwm1xl1JCkjpYbCLO_gPn3/view?usp=sharing

Change permissions to see toolbar

---

config/local/migrate_plus.migration.hwc_crm_partner.yml
config/local/migrate_plus.migration_group.hwc_crm_migration.yml

Base de datos despues de lanzar `drush cim --partial --source=modules/custom/hwc_crm_migration/config/optional -l oira -y`
https://drive.google.com/file/d/1NLHcx8BNlf3egBv3HBmMN5kS3pDa1eRh/view?usp=sharing

migracion modificada

---

config/sync/field.field.node.news.body.yml
config/sync/views.view.moderated_content.yml

DB for fixing issue MOIRA-189
https://drive.google.com/file/d/1NpefUzFybCXYeq76Vw2YXJWSpv77ncqx/view?usp=sharing

Oira jira issues

---

themes/custom/oira_theme/templates/content/node--partner--full.html.twig

Fix for https://jira.osha.europa.eu/browse/MOIRA-208

Fix for issue MOIRA-208

---

config/sync/core.entity_view_display.media.collaboration_items.media_library.yml
config/sync/tour.tour.block-layout.yml
config/sync/tour.tour.language-add.yml
config/sync/tour.tour.language-edit.yml
config/sync/tour.tour.language.yml
config/sync/tour.tour.locale.yml
config/sync/tour.tour.search-api-index-fields.yml
config/sync/tour.tour.search-api-index-form.yml
config/sync/tour.tour.search-api-index-processors.yml
config/sync/tour.tour.search-api-index.yml
config/sync/tour.tour.search-api-server-form.yml
config/sync/tour.tour.search-api-server.yml
config/sync/tour.tour.views-ui.yml
config/sync/views.view.oira_ws.yml
config/sync/views.view.search.yml
config/sync/workflows.workflow.oira.yml

Config for MOIRA-305
Config for MOIRA-318
Config for MOIRA-294

Oira fixes

---

config/staging/matomo.settings.yml
config/sync/core.entity_form_display.media.image.default.yml
config/sync/core.entity_form_display.media.image.media_library.yml
config/sync/core.entity_view_display.media.image.article_image.yml
config/sync/core.entity_view_display.media.image.colorbox_image.yml
config/sync/core.entity_view_display.media.image.default.yml
config/sync/core.entity_view_display.media.image.media_library.yml
config/sync/field.field.media.image.field_caption.yml
config/sync/field.storage.media.field_caption.yml
config/sync/media.type.image.yml
config/sync/views.view.news.yml
config/sync/views.view.oira_ws.yml
config/sync/views.view.promotional_resources_search.yml
config/sync/views.view.search.yml

Relates to 
MDR-4122 | OiRA - Analisis: position of caption fields under pictures in news, promotional items etc.....

20220126 MDR-4804
